# Generated by Django 3.2.9 on 2022-08-28 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedbook',
            name='book',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.book'),
        ),
    ]
