# Generated by Django 4.1 on 2022-08-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, default='Not selected', max_length=100, null=True),
        ),
    ]
