# Generated by Django 3.2.9 on 2022-08-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_addreadbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='finished_reading',
        ),
        migrations.RemoveField(
            model_name='book',
            name='started_reading',
        ),
    ]
