# Generated by Django 3.2.9 on 2022-09-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_savedbook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='added_books_count',
            field=models.IntegerField(default=0),
        ),
    ]
