# Generated by Django 3.2.9 on 2022-09-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_person_added_books_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='read_book_count',
            field=models.IntegerField(default=0),
        ),
    ]
