# Generated by Django 3.2.9 on 2022-08-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
