# Generated by Django 4.1 on 2022-08-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreadbook',
            name='finished_reading',
            field=models.DateField(blank=True, null=True),
        ),
    ]
