# Generated by Django 4.1 on 2022-08-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_addreadbook_finished_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreadbook',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
