# Generated by Django 3.2.9 on 2022-08-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='read_books_count',
        ),
    ]
