# Generated by Django 4.1 on 2022-09-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='no_book_image_015.gif', null=True, upload_to='images/'),
        ),
    ]
