# Generated by Django 4.1 on 2022-08-27 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_app', '0007_remove_savedbook_book_savedbook_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedbook',
            old_name='title',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='savedbook',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
