# Generated by Django 3.2.9 on 2022-08-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_auto_20220822_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='user',
            new_name='profile',
        ),
    ]
