# Generated by Django 4.1 on 2022-08-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_rename_title_savedbook_book_alter_savedbook_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedbook',
            old_name='book',
            new_name='title',
        ),
    ]
