# Generated by Django 3.2.9 on 2022-08-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_alter_person_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='read',
        ),
    ]
