# Generated by Django 3.2.9 on 2022-08-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0010_remove_book_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='read_books',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
