# Generated by Django 4.1 on 2022-08-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0010_alter_savedbook_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedbook',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
