# Generated by Django 3.2.9 on 2022-09-19 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0010_person_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='person',
            name='following',
        ),
        migrations.CreateModel(
            name='FriendShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='library_app.person')),
                ('following', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='library_app.person')),
            ],
        ),
    ]
