# Generated by Django 3.2.9 on 2022-09-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0011_auto_20220919_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='followers',
            new_name='followed_by',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='following',
            new_name='sent_by',
        ),
    ]
