# Generated by Django 3.2.9 on 2022-08-24 17:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0011_alter_person_read_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='read_books_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=None), blank=True, null=True, size=None),
        ),
    ]
