# Generated by Django 3.2.9 on 2022-09-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0012_auto_20220919_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
