# Generated by Django 3.2.9 on 2022-09-22 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0013_friendship_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='library_app.book')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.person')),
            ],
        ),
    ]
