# Generated by Django 3.2.9 on 2022-09-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0014_favouritebooks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='sent_by',
            new_name='sent_to',
        ),
    ]
