# Generated by Django 3.2.9 on 2022-09-23 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0015_rename_sent_by_friendship_sent_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='followed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='library_app.person'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='sent_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='library_app.person'),
        ),
    ]
