# Generated by Django 3.2.9 on 2022-09-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0016_auto_20220923_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='follow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow', to='library_app.person'),
        ),
    ]
